name: CI Pipeline for OrangeHRM Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    # Step 3: Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Step 4: Build the solution
    - name: Build Solution
      run: dotnet build --no-restore --configuration Release

    # Step 5: Run tests
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
