name: CI Pipeline for OrangeHRM Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: windows-latest  # Uses Windows runner for compatibility with automation libraries.

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x  # Adjust to the version you're using.

    # Step 3: Restore project dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the solution
    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    # Step 5: Run NUnit tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
